name:                kore-parser
version:             0.0.1.0
github:              "kframework/kore"
license:             OtherLicense
license-file:        LICENSE
author:              "Virgil Serbanuta"
maintainer:          "virgil.serbanuta@runtimeverification.com"
copyright:           "2018 Runtime Verification Inc"
category:            Parser

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/kframework/src/haskell/parser/README.md>

dependencies:
- base >= 4.7 && < 5
- parsec >=3.1 && <3.2
- attoparsec >=0.13 && <0.14
- bytestring >=0.10 && <0.11
- array
- bytestring-trie
- kore-ast

library:
  source-dirs: src

executables:
  kore-parser:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kore-parser

tests:
  kore-parser-test:
    main:                AllParserTests.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kore-parser
    - tasty
    - tasty-hunit
    - tasty-golden
    - filepath
