name:                kore-ast
version:             0.0.1.0
github:              "kframework/kore"
license:             OtherLicense
license-file:        LICENSE
author:              "Virgil Serbanuta"
maintainer:          "virgil.serbanuta@runtimeverification.com"
copyright:           "2018 Runtime Verification Inc"
category:            Parser

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/kframework/src/haskell/parser/README.md>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:

tests:
